/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/cqc_receiver': {
		/**
		 * Receive a CQC hook from PLANTdataHUB
		 * @description Accepts the CQC webhook payload, pulls the referenced RO-Crate from GitLab, stores a new submission entry in memory, and returns a "follow me" URL the user should be redirected to for license agreement / review.
		 */
		post: operations['receiveCqcHook'];
	};
	'/{submissionID}/get_metadata': {
		/**
		 * Get generated metadata for a submission
		 * @description Returns metadata derived from the stored RO-Crate for the given submission, for display/editing in the submission tool UI. Requires dlaRead=true, indicating the user has opened/acknowledged the data license agreement.
		 */
		get: operations['getMetadata'];
	};
	'/{submissionID}/get_arcfiles': {
		/**
		 * Get ARC files for a submission
		 * @description Returns the list of ARC files (either inline bytes or LFS-resolvable URLs) associated with the submission's RO-Crate. Requires finishWebUI=true, indicating the user has clicked "finish" in the submission tool UI.
		 */
		get: operations['getArcFiles'];
	};
}

export type webhooks = Record<string, never>;

export interface components {
	schemas: {
		/** @description Payload sent by PLANTdataHUB's CQC hook. */
		CqcHookPayload: {
			/** @description Identifier of the PLANTdataHUB project. */
			project_id: string;
			/** @description Private GitLab token used to fetch the RO-Crate (sent as PRIVATE-TOKEN header). */
			gitlab_token: string;
			/**
			 * Format: uri
			 * @description URL from which the RO-Crate JSON-LD document can be fetched.
			 */
			ro_crate_url: string;
			[key: string]: unknown;
		};
		/**
		 * @example {
		 *   "follow_me": "http://dmz-web-140.ipk-gatersleben.de:10042/submit?submission_id=b016cd8d-ae93-40cf-9c2b-19bddf32597b&access_token=41c86f94-a46e-4460-b107-950f61c1771fac70bd2c-cb91-485c-9f0b-e35bd16d012d"
		 * }
		 */
		FollowMeResponse: {
			/**
			 * Format: uri
			 * @description URL the user should be redirected to, where they review/accept the license agreement before metadata is released.
			 */
			follow_me?: string;
		};
		Author: {
			firstName?: string;
			lastName?: string;
			affiliation?: string;
			/** @description ORCID identifier/URL of the author. */
			orcid?: string;
			city?: string;
			address?: string;
			/**
			 * @description First author found is "Creator"; all subsequent authors are "Contributor".
			 * @enum {string}
			 */
			role?: 'Creator' | 'Contributor';
		};
		Metadata: {
			title?: string;
			description?: string;
			authors?: components['schemas']['Author'][];
			language?: string;
			subjects?: string[];
			/** @example CC-BY-4.0 */
			license?: string;
			/** @description ISO date string, empty if no embargo. */
			embargoDate?: string;
		};
		/**
		 * @example {
		 *   "dlaRead": true,
		 *   "metadata": {
		 *     "title": "SHAPE P2 Phenotyping Trials",
		 *     "description": "This is a description of the SHAPE Phase 2 phenotyping trials dataset",
		 *     "authors": [
		 *       {
		 *         "firstName": "Manuel",
		 *         "lastName": "Feser",
		 *         "affiliation": "Leibniz-Institut fur Pflanzengenetik und Kulturpflanzenforschung (IPK), BIT",
		 *         "orcid": "http://orcid.org/0000-0001-6546-1818",
		 *         "city": "",
		 *         "address": "",
		 *         "role": "Creator"
		 *       }
		 *     ],
		 *     "language": "",
		 *     "subjects": [],
		 *     "license": "CC-BY-4.0",
		 *     "embargoDate": ""
		 *   },
		 *   "filePaths": [],
		 *   "file_transfer_mode": "rocrate"
		 * }
		 */
		MetadataResponse: {
			/** @example true */
			dlaRead?: boolean;
			metadata?: components['schemas']['Metadata'];
			/** @description Relative paths of all File entities found in the RO-Crate. */
			filePaths?: string[];
			/** @example rocrate */
			file_transfer_mode?: string;
		};
		/**
		 * @description A file in the ARC format. Either inline byte content (BYTES) or a resolvable LFS URL (LFS), depending on "type".
		 *
		 * @example {
		 *   "path": "assays/assay1/data.csv",
		 *   "type": "LFS",
		 *   "content": null,
		 *   "url": "https://lfs-resolver.nfdi4plants.org/presigned-url/?oid=abc123..."
		 * }
		 */
		ArcFile: {
			/** @description Relative path of the file within the RO-Crate/ARC. */
			path?: string;
			/**
			 * @description BYTES = content is included inline; LFS = resolve via url.
			 * @enum {string}
			 */
			type?: 'BYTES' | 'LFS';
			/**
			 * Format: byte
			 * @description Base64-encoded file content. Present only when type is BYTES.
			 */
			content?: string | null;
			/**
			 * Format: uri
			 * @description Presigned/resolver URL for LFS-tracked files. Present only when type is LFS.
			 */
			url?: string | null;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
	/**
	 * Receive a CQC hook from PLANTdataHUB
	 * @description Accepts the CQC webhook payload, pulls the referenced RO-Crate from GitLab, stores a new submission entry in memory, and returns a "follow me" URL the user should be redirected to for license agreement / review.
	 */
	receiveCqcHook: {
		requestBody: {
			content: {
				'application/json': components['schemas']['CqcHookPayload'];
			};
		};
		responses: {
			/** @description Submission accepted; redirect URL returned. */
			200: {
				content: {
					'application/json': components['schemas']['FollowMeResponse'];
				};
			};
			/** @description Internal server error (e.g. RO-Crate fetch failed). */
			500: {
				content: {
					'text/plain': string;
				};
			};
		};
	};
	/**
	 * Get generated metadata for a submission
	 * @description Returns metadata derived from the stored RO-Crate for the given submission, for display/editing in the submission tool UI. Requires dlaRead=true, indicating the user has opened/acknowledged the data license agreement.
	 */
	getMetadata: {
		parameters: {
			query?: {
				/** @description Must be true to retrieve metadata (indicates the DLA was read/opened). */
				dlaRead?: boolean;
			};
			path: {
				/** @description UUID identifying the submission. */
				submissionID: string;
			};
		};
		responses: {
			/** @description Metadata for the submission. */
			200: {
				content: {
					'application/json': components['schemas']['MetadataResponse'];
				};
			};
			/** @description Invalid parameter, or dlaRead not true. */
			400: {
				content: {
					'text/plain': string;
				};
			};
			/** @description Submission not found. */
			404: {
				content: {
					'text/plain': string;
				};
			};
			/** @description Internal server error. */
			500: {
				content: {
					'text/plain': string;
				};
			};
		};
	};
	/**
	 * Get ARC files for a submission
	 * @description Returns the list of ARC files (either inline bytes or LFS-resolvable URLs) associated with the submission's RO-Crate. Requires finishWebUI=true, indicating the user has clicked "finish" in the submission tool UI.
	 */
	getArcFiles: {
		parameters: {
			query?: {
				/** @description Must be true to retrieve ARC files (indicates the user clicked "finish"). */
				finishWebUI?: boolean;
			};
			path: {
				/** @description UUID identifying the submission. */
				submissionID: string;
			};
		};
		responses: {
			/** @description List of ARC files for the submission. */
			200: {
				content: {
					'application/json': components['schemas']['ArcFile'][];
				};
			};
			/** @description Invalid parameter, or finishWebUI not true. */
			400: {
				content: {
					'text/plain': string;
				};
			};
			/** @description Submission not found. */
			404: {
				content: {
					'text/plain': string;
				};
			};
			/** @description Internal server error. */
			500: {
				content: {
					'text/plain': string;
				};
			};
		};
	};
}
